/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../src/code.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_mult_shouldReturnZero(void);
extern void test_mult_shouldReturnTen(void);
extern void test_divide_shouldReturnZero(void);
extern void test_factorial_shouldReturnOne(void);
extern void test_factorial_shouldReturnTwo(void);
extern void test_factorial_shouldReturnSix(void);
extern void test_factorial_shouldReturn120(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_code.c");
  run_test(test_mult_shouldReturnZero, "test_mult_shouldReturnZero", 13);
  run_test(test_mult_shouldReturnTen, "test_mult_shouldReturnTen", 20);
  run_test(test_divide_shouldReturnZero, "test_divide_shouldReturnZero", 27);
  run_test(test_factorial_shouldReturnOne, "test_factorial_shouldReturnOne", 34);
  run_test(test_factorial_shouldReturnTwo, "test_factorial_shouldReturnTwo", 40);
  run_test(test_factorial_shouldReturnSix, "test_factorial_shouldReturnSix", 45);
  run_test(test_factorial_shouldReturn120, "test_factorial_shouldReturn120", 50);

  return UnityEnd();
}
