name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job: Unit test suite
  unit-tests:
    name: "Unit Tests"

    runs-on: ubuntu-latest

    steps:

      # Install Ruby Testing Tools
      - name: Setup Ruby Testing Tools
        run: |
          sudo gem install rspec
          sudo gem install rubocop -v 0.57.2

      # Checks out repository
      - name: Checkout
        uses: actions/checkout@v2

      # Run Tests
      - name: Run Unit Tests
        run: make all

